package com.jaynewstrom.gastracker.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.util.ArrayList;
import java.util.List;
// KEEP INCLUDES END

/**
 * Entity mapped to table FUEL_GRADE.
 */
public class FuelGrade {

    private long id;
    /** Not-null value. */
    private String name;

    // KEEP FIELDS - put your custom fields here
    private static final String JSON_KEY_ID = "id";
    private static final String JSON_KEY_NAME = "name";
    // KEEP FIELDS END


    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    // KEEP METHODS - put your custom methods here
    FuelGrade() {
        /** used by {@link FuelGradeDao} */
    }

    private FuelGrade(long id, String name) {
        this.id = id;
        this.name = name;
    }

    public static List<FuelGrade> insert(JSONArray jsonArray, FuelGradeDao fuelGradeDao) throws JSONException {
        int fuelGradesToAddLength = jsonArray.length();

        List<FuelGrade> fuelGrades = new ArrayList<FuelGrade>(fuelGradesToAddLength);


        for (int i = 0; i < fuelGradesToAddLength; i++) {
            JSONObject jsonObject = jsonArray.getJSONObject(i);

            long id = jsonObject.getLong(JSON_KEY_ID);
            String name = jsonObject.getString(JSON_KEY_NAME);

            fuelGrades.add(new FuelGrade(id, name));
        }

        fuelGradeDao.insertInTx(fuelGrades);

        return fuelGrades;
    }
    // KEEP METHODS END

}
